version: 0.2

phases: 
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 105289381504.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - docker build -t coworking-python-app .
      - docker tag coworking-python-app:latest 105289381504.dkr.ecr.ap-southeast-1.amazonaws.com/coworking-python-app:latest
  post_build:
    commands:
      - docker push 105289381504.dkr.ecr.ap-southeast-1.amazonaws.com/coworking-python-app:latest